name: Matlab Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: '30 5 * * 5'

jobs:
  unit-tests:
    name: Run Matlab Unit Tests
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@main

      - name: Setup Matlab environment
        uses: matlab-actions/setup-matlab@v1

      - name: Run tests and generate artifacts
        uses: matlab-actions/run-tests@v1.3.0
        with:
          source-folder: source
          test-results-junit: test-results/results.xml
          code-coverage-cobertura: code-coverage/coverage.xml

      - name: Check coverage
        uses: codecov/codecov-action@v3
        with:
          files: code-coverage/coverage.xml
          fail_ci_if_error: true 
